# Generated by Django 5.1.3 on 2024-11-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='is_featured',
            new_name='id_feacherd',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(upload_to='uploads/%x/%m/%d'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.IntegerField(choices=[('draft', 'Draft'), ('public', 'Published')], default='draft'),
        ),
    ]
