# Generated by Django 5.1.3 on 2024-11-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blogs_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='id_feacherd',
            new_name='is_feacherd',
        ),
    ]
