# Generated by Django 5.1.3 on 2024-11-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_id_feacherd_blogs_is_feacherd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='is_feacherd',
            new_name='is_featured',
        ),
    ]
